name: Build & Publish Cameras Tileset

on:
  workflow_dispatch: {}          # lets you run it manually
  schedule:
    - cron: "17 6 * * *"        # runs daily at 06:17 UTC
  push:
    branches: [ main ]
    paths:
      - "data/**"
      - "scripts/**"
      - "tilesets/**"
      - ".github/workflows/cameras-tileset.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 1) Produce data/cameras.geojson from your raw feed
      - name: Transform -> cameras.geojson
        run: |
          node scripts/transform_cameras.mjs
          ls -lh data/cameras.geojson

      # 2) Install Mapbox tilesets CLI
      - name: Install Mapbox tilesets CLI
        run: python3 -m pip install --upgrade pip mapbox-tilesets

      # 3) Upload/replace the tileset source from GeoJSON
      - name: Upload tileset source
        env: { MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_SECRET_TOKEN }} }
        run: |
          tilesets upload-source masonzbirkett cameras_src data/cameras.geojson --replace

      # 4) Create the tileset (ENABLE THIS TRUE FOR THE FIRST RUN ONLY)
      - name: Create tileset (one-time)
        if: ${{ true }}
        env: { MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_SECRET_TOKEN }} }
        run: |
          tilesets create masonzbirkett.cameras --recipe tilesets/cameras.recipe.json --name "Flock Cameras"

      # 5) Publish (build) the tileset
      - name: Publish tileset
        env: { MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_SECRET_TOKEN }} }
        run: |
          tilesets publish masonzbirkett.cameras
