name: Build & Publish Cameras PMTiles

on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 6 * * *"  # daily at 06:17 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Transform the sample/raw feed into a clean cameras.geojson
      - name: Transform -> cameras.geojson (from sample/raw feed)
        run: |
          node scripts/transform_cameras.mjs
          ls -lh data/cameras.geojson

      # Install tools. IMPORTANT: add ~/.local/bin to PATH so 'pmtiles' works now and later.
      - name: Install tippecanoe & pmtiles
        run: |
          sudo apt-get update
          sudo apt-get install -y tippecanoe python3-pip
          python3 -m pip install --user --upgrade pmtiles
          export PATH="$HOME/.local/bin:$PATH"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          which pmtiles || true
          ls -l "$HOME/.local/bin" || true

      # Build MBTiles with stable layer name "cameras"
      - name: Build MBTiles (layer name "cameras")
        run: |
          tippecanoe -o data/cameras.mbtiles \
            -zg -l cameras \
            --drop-densest-as-needed --coalesce-densest-as-needed \
            --no-feature-limit --no-tile-size-limit \
            -y dir -y id -y type -y last_seen \
            data/cameras.geojson
          ls -lh data/cameras.mbtiles

      # Convert MBTiles -> PMTiles using the Python module (doesn't rely on CLI on PATH)
      - name: Convert to PMTiles
        run: |
          python3 -m pmtiles.cli convert data/cameras.mbtiles cameras.pmtiles
          ls -lh cameras.pmtiles


      # Publish the file to the gh-pages branch at /tiles/cameras.pmtiles
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: site
          fetch-depth: 0

      - name: Publish to gh-pages/tiles/
        run: |
          mkdir -p site/tiles
          cp -f cameras.pmtiles site/tiles/cameras.pmtiles
          cd site
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tiles/cameras.pmtiles
          git commit -m "Update cameras.pmtiles $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push
