name: Build & Publish Cameras PMTiles

on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 6 * * *"        # nightly
  push:
    branches: [ main ]
    paths:
      - 'data/**'
      - 'scripts/**'
      - '.github/workflows/cameras-pmtiles.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 1) Normalize your input to data/cameras.geojson (ensures a 'dir' field)
      - name: Transform -> cameras.geojson
        run: |
          node scripts/transform_cameras.mjs
          ls -lh data/cameras.geojson

      # 2) Install Tippecanoe (has native PMTiles output)
      - name: Install tippecanoe
        run: |
          sudo apt-get update
          sudo apt-get install -y tippecanoe

      # 3) Build PMTiles directly (NO separate convert step needed)
      - name: Build PMTiles (layer name "cameras")
        run: |
          tippecanoe -o cameras.pmtiles \
            -zg -l cameras \
            --drop-densest-as-needed --coalesce-densest-as-needed \
            --no-feature-limit --no-tile-size-limit \
            -y dir -y id -y type -y last_seen \
            data/cameras.geojson
          ls -lh cameras.pmtiles

      # 4) Publish PMTiles to the gh-pages branch at /tiles/cameras.pmtiles
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: site
          fetch-depth: 0

      - name: Publish to gh-pages/tiles/
        run: |
          set -e
          mkdir -p site/tiles
          cp -f cameras.pmtiles site/tiles/cameras.pmtiles
          cd site
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tiles/cameras.pmtiles
          git commit -m "Update cameras.pmtiles $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push


